{
    'name': 'Addoons Aliquid',
    'version': '1.0',
    'category': 'all',
    'description': 'Addoons Aliquid',
    'summary': 'Personalizzazione Aliquid',
    'author': 'addOons srl',
    'website': 'www.addoons.it',
    'support': 'support@addoons.it',
    'depends': [
        'base', 'account', 'sale', 'purchase', 'product', 'sale_management', 'hr' ,'sale_subscription', 'sale_subscription_dashboard','hr_timesheet', 'sale_timesheet', 'helpdesk', 'report_xlsx', 'website', 'helpdesk_timesheet', 'helpdesk_sale', 'l10n_it_fatturapa', 'l10n_it_fatturapa_sale',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/assets.xml',
        'views/res_users.xml',
        'security/security.xml',
        'views/res_partner.xml',
        'views/sale_subscription.xml',
        'views/sale_order.xml',
        'views/account_payment_term.xml',
        'views/account_move_line.xml',
        'views/ticket_portal.xml',
        'views/hr_timesheet.xml',
        'reports/report_invoice.xml',
        'views/purchase_order.xml',
        'views/hr_employee.xml',
        'views/helpdesk_ticket.xml',
        'views/account_move.xml',
        'views/portal_templates.xml',
        'views/sale_portal.xml',
        'views/timesheet_plan.xml',
        'reports/report_ticket_xls.xml',
        'wizards/wizard_export_ticket.xml',
    ],

    'installable': True,

}
